// Generate embedded LVGL fonts for the Faraday brand typography.
//
// Brand faces:
//   - Orbitron  -> headlines / logo wordmark (all caps)
//   - Rajdhani  -> technical labels / buttons / chips (all caps, wide)
//   - Inter     -> body text, addresses, amounts
//
// Output: src/fonts/faraday_<face>_<size>.c  (LVGL C arrays, bpp 4, ASCII range)
// Variable name in each file matches the file base, e.g. `faraday_orbitron_28`.
//
// Usage:  node scripts/gen_fonts.mjs
// Requires: network access (downloads OFL TTFs once into scripts/.fontcache),
//           and `npx lv_font_conv` (Node available).
//
// Brand-font labels intentionally avoid LVGL/FontAwesome symbol glyphs, so the
// fonts only need the printable ASCII range (0x20-0x7E). This keeps the build
// self-contained and the font tables small.

import { execFileSync } from "node:child_process";
import { mkdirSync, existsSync, writeFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const cacheDir = join(__dirname, ".fontcache");
const outDir = join(repoRoot, "src", "fonts");
const includeDir = join(repoRoot, "include");

mkdirSync(cacheDir, { recursive: true });
mkdirSync(outDir, { recursive: true });

// Static/variable TTFs from the upstream Google Fonts repo (OFL licensed).
const sources = {
  orbitron: "https://raw.githubusercontent.com/google/fonts/main/ofl/orbitron/Orbitron%5Bwght%5D.ttf",
  inter: "https://raw.githubusercontent.com/google/fonts/main/ofl/inter/Inter%5Bopsz%2Cwght%5D.ttf",
  rajdhani: "https://raw.githubusercontent.com/google/fonts/main/ofl/rajdhani/Rajdhani-SemiBold.ttf",
};

// face -> list of pixel sizes to embed.
const faces = {
  orbitron: [20],
  rajdhani: [14, 18],
  inter: [12, 14, 16],
};

const RANGE = "0x20-0x7E"; // printable ASCII only
const BPP = 4;

async function download(url, dest) {
  if (existsSync(dest) && statSync(dest).size > 1024) {
    console.log(`cache hit: ${dest}`);
    return;
  }
  console.log(`downloading: ${url}`);
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`download failed ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 1024) throw new Error(`suspiciously small file (${buf.length} B) for ${url}`);
  writeFileSync(dest, buf);
  console.log(`  saved ${buf.length} bytes -> ${dest}`);
}

function convert(face, ttf, size) {
  const name = `faraday_${face}_${size}`;
  const out = join(outDir, `${name}.c`);
  const args = [
    "lv_font_conv@1.5.3",
    "--bpp", String(BPP),
    "--size", String(size),
    "--font", ttf,
    "--range", RANGE,
    "--format", "lvgl",
    "--force-fast-kern-format",
    "--no-compress",
    "--lv-include", "lvgl.h",
    "-o", out,
  ];
  console.log(`converting ${name} ...`);
  execFileSync("npx", args, { stdio: "inherit", shell: process.platform === "win32" });
  return name;
}

const generated = [];
for (const [face, url] of Object.entries(sources)) {
  const ttf = join(cacheDir, `${face}.ttf`);
  await download(url, ttf);
  for (const size of faces[face]) {
    generated.push(convert(face, ttf, size));
  }
}

// Emit a single header declaring every generated face.
const guard = "FARADAY_FONTS_H";
const lines = [
  "// Auto-generated by scripts/gen_fonts.mjs - do not edit by hand.",
  "#pragma once",
  "",
  "#include <lvgl.h>",
  "",
  "#ifdef __cplusplus",
  'extern "C" {',
  "#endif",
  "",
];
for (const name of generated) lines.push(`extern const lv_font_t ${name};`);
lines.push("", "#ifdef __cplusplus", "}", "#endif", "");
writeFileSync(join(includeDir, "fonts.h"), lines.join("\n"));

console.log(`\nDone. Generated ${generated.length} font faces:`);
for (const n of generated) console.log(`  - ${n}`);
console.log(`Header: include/fonts.h`);
