#!/usr/bin/env python3
"""Convert the Faraday logo banner into an LVGL TRUE_COLOR_ALPHA C image.

The source art is a white shield + "FARADAY" wordmark on black. We keep the
original (white) color and derive the alpha channel from luminance, so the
black field becomes transparent and the logo composites cleanly onto the
Faraday-black UI. The image is emitted at its final on-screen size with NO
runtime zoom/recolor (transforming alpha images was the prior invisibility
cause), which keeps rendering crisp and cheap.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_PNG = REPO_ROOT / "assets" / "faraday-logo.png"
OUT_C = REPO_ROOT / "src" / "logo_faraday.c"
OUT_H = REPO_ROOT / "include" / "logo_faraday.h"
VAR = "faraday_logo"

TARGET_W = 248          # final wordmark width on the 320px panel
MAX_H = 76              # clamp height if the crop is unexpectedly tall
LUMA_CROP = 18          # luminance threshold for autocrop / alpha floor


def luma(r: int, g: int, b: int) -> int:
    return (r * 299 + g * 587 + b * 114) // 1000


def autocrop(im: Image.Image) -> Image.Image:
    px = im.load()
    w, h = im.size
    minx, miny, maxx, maxy = w, h, 0, 0
    found = False
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if luma(r, g, b) > LUMA_CROP:
                found = True
                minx = min(minx, x); maxx = max(maxx, x)
                miny = min(miny, y); maxy = max(maxy, y)
    if not found:
        return im
    pad = 4
    minx = max(0, minx - pad); miny = max(0, miny - pad)
    maxx = min(w - 1, maxx + pad); maxy = min(h - 1, maxy + pad)
    return im.crop((minx, miny, maxx + 1, maxy + 1))


def rgb565_le(r: int, g: int, b: int) -> tuple[int, int]:
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return v & 0xFF, (v >> 8) & 0xFF


def main() -> int:
    im = Image.open(SRC_PNG).convert("RGBA")
    im = autocrop(im)
    w, h = im.size
    scale = TARGET_W / w
    new_w = TARGET_W
    new_h = round(h * scale)
    if new_h > MAX_H:
        scale = MAX_H / h
        new_h = MAX_H
        new_w = round(w * scale)
    im = im.resize((new_w, new_h), Image.LANCZOS)
    w, h = im.size
    px = im.load()

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            alpha = luma(r, g, b)            # white -> opaque, black -> clear
            alpha = 0 if alpha < 6 else alpha
            lo, hi = rgb565_le(r, g, b)
            data += bytes((lo, hi, min(alpha, 255)))

    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        rows.append("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",")
    body = "\n".join(rows)

    c = f"""// Auto-generated by scripts/gen_logo.py - do not edit by hand.
// Source: assets/faraday-logo.png  (rendered {w}x{h}, TRUE_COLOR_ALPHA).
#include "lvgl.h"

const LV_ATTRIBUTE_MEM_ALIGN uint8_t {VAR}_map[] = {{
{body}
}};

const lv_img_dsc_t {VAR} = {{
    .header = {{
        .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
        .always_zero = 0,
        .reserved = 0,
        .w = {w},
        .h = {h},
    }},
    .data_size = {w * h} * LV_IMG_PX_SIZE_ALPHA_BYTE,
    .data = {VAR}_map,
}};
"""

    hdr = f"""// Auto-generated by scripts/gen_logo.py - do not edit by hand.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {{
#endif

// Faraday logo (shield + wordmark), {w}x{h}, white art with luminance alpha.
extern const lv_img_dsc_t {VAR};

#ifdef __cplusplus
}}
#endif
"""

    OUT_C.write_text(c, encoding="utf-8")
    OUT_H.write_text(hdr, encoding="utf-8")
    print(f"Wrote {OUT_C} ({w}x{h}, {len(data)} bytes)")
    print(f"Wrote {OUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
