// Auto-generated by scripts/gen_fonts.mjs - do not edit by hand.
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t faraday_orbitron_20;
extern const lv_font_t faraday_inter_12;
extern const lv_font_t faraday_inter_14;
extern const lv_font_t faraday_inter_16;
extern const lv_font_t faraday_rajdhani_14;
extern const lv_font_t faraday_rajdhani_18;

#ifdef __cplusplus
}
#endif
