// Auto-generated by scripts/gen_logo.py - do not edit by hand.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Faraday logo (shield + wordmark), 248x65, white art with luminance alpha.
extern const lv_img_dsc_t faraday_logo;

#ifdef __cplusplus
}
#endif
